language: python
branches:
  only:
    - master
python:
  - "2.7"
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 15
script:
  - export GDAL_DATA=/home/travis/.conda/envs/birdhouse/share/gdal 
  - make test
#after_success:
# - coveralls
