language: python
branches:
  only:
    - develop
    - master
python:
  - "2.7"
sudo: false
install:
  - make install
script:
  - export GDAL_DATA=/home/travis/.conda/envs/birdhouse/share/gdal; make test
#after_success:
# - coveralls
