name: flyingpigeon
channels:
- defaults
- birdhouse
# cartopy nco cdo ... etc
#- ioos
- conda-forge
# ocgis
- nesii
# the r hell ...
- r
- bioconda  # r-mclust
dependencies:
- python=2.7.12       # comes with ocgis
- libxslt=1.1.28      #- psutil=4.3.1        # installed in ~/anaconda 
- lxml=3.6.4=py27_0
- gcc=4.8.5            
#- cffi#=1.7.0        # required for pyyaml/cryptography
- pyopenssl=0.16.0
- cryptography=1.5
#- icu=54.1           # comes with
#- libiconv=1.14      # comes with
#tests
- pytest#=2.9.2
#docs
- sphinx
- sphinx_rtd_theme
#ipython
- ipython # =5.1.     # comes with ??
# wps
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent
- pywps=3.2.6=py27_1       # patch without gdal dedendency
- mako=1.0
# # misc
- pywget=2.2
- pyyaml=3.12
# # cdo                    
- cdo=1.7.1
- python-cdo=1.3.0
# - jpeg=9b                # allready there 
# numeric
- scipy=0.18.0=np111py27_0            
- pandas=0.18.1               
- statsmodels=0.6.1      
- scikit-learn=0.17.1    
# # cartopy
- cartopy=0.14.2        
- iris=1.9.2          
# ocgis ... drives me nuts :(
- ocgis-next=1.4.0.dev1=py27_1
- esmpy=7.0.0=py27_1
- esmf=7.0.0
#- icclim=4.2.5     # comes with ocgis 
#- netcdf4=1.2.4    # comes with ocgis
#- libnetcdf=4.4.1  # comes with ocgis
- gdal=2.1.1        # comes with ocgis  
#- numpy=1.11        # comes with ocgis
#- proj.4=4.9.2      # comes with ocgis
#- udunits2=2.2.20   # comes with ocgis
#- geos=3.5.0        # comes with ocgis
#- cf_units=1.1.2    # comes with ocgis
#- curl=7.49.1       # comes with ocgis
- fiona=1.7.0       # comes with ocgis
#- libspatialindex=1.8.5  # comes with ocgis
#- munch=2.0.4       # comes with ocgis
#- rtree=0.8.2       # comes with ocgis
# # analogue
- castf90=0.1.2
- netcdf-fortran=4.4.3
- nco=4.5.5
# r
- r#=3.2.2 
- rpy2#=2.8.1
- r-mclust#=5.1
- r-ncdf4#=1.13
- r-fields#=8.4_1
#- r-base=3.3.1
#- r-gridextra=2.2.1 # in conflict with python 2.7.12
- r-cairo=1.5_9
- pip:
  - genshi==0.7
  - pygbif==0.1.4  # comes with scipy?
  #- cdo==1.3.0      # comes with scipy?
  - sphinx-autoapi==0.4.0
