name: flyingpigeon
channels:
- defaults
- birdhouse
# cartopy nco etc
- ioos
# ocgis
- nesii
# the r hell ...
- r
- bioconda
dependencies:
- python=2.7.12
- gcc=4.8.5
- pyopenssl=0.16.0
- cryptography=1.4
- icu=54.1
- libiconv=1.14
# tests
- pytest
- nose
# docs
- sphinx
# ipython
- ipython=4.2.0
# wps
- nginx=1.10.1
- supervisor
- pywps=3.2.6
- mako
# misc
- pywget
- pyyaml
# cdo
- cdo=1.7.0
# numeric
- pandas=0.18.1
- statsmodels=0.6.1
- scikit-learn=0.17.1
# cartopy
- cartopy=0.14.2
- iris=1.9.2
# ocgis ... drives me nuts :(
- ocgis-next=1.4.0
- esmpy=7.0.0 
- icclim=4.1.1
- netcdf4=1.2.2
- gdal=1.11.3
- numpy=1.10.4
- proj4=4.9.2
- udunits2=2.2.20
- geos=3.4.2
- cf_units=1.1
- curl=7.45
- fiona=1.6.3
# analogue
- castf90=0.1.2
- nco=4.5.5
# r
- r=3.2.2 
- rpy2=2.7.0
- r-mclust=5.1
- r-ncdf4=1.13
- r-fields=8.4
- pip:
  - genshi==0.7
  - pygbif==0.1.4
  - cdo==1.3.0
