name: flyingpigeon
channels:
- conda-forge
- defaults
- birdhouse
# cartopy nco cdo ... etc
# - ioos
# ocgis
- nesii
# the r hell ...
- r
- bioconda
dependencies:
- python=2.7.12=1
- ipython#=4.2.0
###############################
# c fortran netcdf architecture
###############################
- pyopenssl=0.16.0
- cryptography=1.4
- icu=54.1
- libiconv=1.14
- hdf4=4.2.12=0 
- hdf5=1.8.17=5 
- gcc=4.8.5
- jpeg=9b-0
- json-c=0.12=0
- libgfortran=3.0.0=1                       
- libiconv=1.14=3 
- libnetcdf=4.4.1=0 
- libpng=1.6.24=0
- netcdf-fortran=4.4.3
- nco=4.5.5
- pillow=3.2.0=py27_1
- libtiff=4.0.6=6
- pillow=3.2.0
- pyqt=4.11.4    
- mkl=11.3.3=0                      
- ncurses=5.9=9
- netcdf4=1.2.4=np111py27_2  
- numpy=1.11.1=py27_0                 
- openjpeg=2.1.0=6
- tk=8.5.19
- zlib=1.2.8=3
#########
# tests
#########
- pytest
##########
# docs
##########
- sphinx
- sphinx_rtd_theme
######
# wps
#####
- nginx=1.10.1
- supervisor=3.1.3
- gunicorn=19.1.0
- gevent
- pywps=3.2.6
- mako
# misc
- pywget
- pyyaml
# cdo #depends with castf90
#- cdo=1.7.0
#- jpeg=8d
###########
# numeric
###########
- pandas#=0.18.1
- statsmodels#=0.6.1
- scikit-learn#=0.17.1
# cartopy
- cartopy#=0.14.2 # conflicts with numpy >1.10
- iris#=1.9.2 # conflicts with numpy >1.10
################################
# ocgis ... drives me nuts :(
################################
- ocgis-next=1.4.0.dev1=py27_2
# - curl=7.49.1=1
# - fiona=1.7.0=np111py27_2
# - gdal=2.1.1#=np111py27_0
# - libgdal=2.1.0=0                       
# - geos=3.5.0-0                       
# - geotiff=1.4.1=0                       
# - giflib=5.1.4=0
# - proj4=4.9.2=0                       
##################
# analogue CASTf90
##################
- castf90=0.1.5
##################
# r
##################
- r=3.2.2 
- rpy2=2.7.0
- r-mclust=5.1
- r-ncdf4=1.13
- r-fields=8.4
- r-gridextra=2.0.0
- r-cairo=1.5_9
- pip:
  - genshi==0.7
  - pygbif==0.1.4
#  - cdo==1.3.0
  - sphinx-autoapi==0.4.0
