name: flyingpigeon_test
channels:
# - defaults
- birdhouse
- conda-forge
# cartopy nco cdo ... etc
#- ioos
# ocgis
- nesii
# the r hell ...
- r
- bioconda
dependencies:
- python=2.7.12=1  #  conda-forge
# - gcc# =4.8.5
# - pyopenssl# =0.16.0
- cryptography=1.5.2
- psutil
- cffi=1.8.3=py27_0
# - libxslt#=1.1.28
# tests
- pytest
# docs
#- sphinx
#- sphinx_rtd_theme
# wps
#- nginx # =1.10.1
#- supervisor # =3.3.1
#- gunicorn # =19.1.0
#- gevent
#- pywps #=3.2.6
#- mako
# misc
#- pywget
#- pyyaml
# cdo #depends with castf90
#- python-cdo
#- cdo=1.7.0
#- jpeg=8d
# numeric
- scipy=0.18.1=np111py27_blas_openblas_200 
- pandas=0.19.0
#- pandas #=0.18.1
#- statsmodels #=0.6.1
- scikit-learn #=0.17.1
# cartopy
#- cartopy #=0.14.2 # conflicts with numpy >1.10
#- iris #=1.9.2 # conflicts with numpy >1.10
##############
## cdo ocgis 
##############
# - backports=1.0=py27_0  
- cdo # =1.7.1=2
# - cf_units=1.1.3=py27_0
# - click=6.6=py27_0
# - click-plugins=1.0.3=py27_0
# - cligj=0.4.0=py27_0  
# - curl=7.49.1=1 #    conda-forge
# - decorator=4.0.10=py27_0  
# - enum34=1.1.6=py27_0  
# - expat=2.1.0=2 #   conda-forge
# - fiona=1.7.0=np111py27_2  #  conda-forge
# - freexl=1.0.2=1  #  conda-forge
# - gdal=2.1.1=np111py27_3  #  conda-forge
# - geos=3.4.2=2  #  conda-forge
# - get_terminal_size=1.0.0=py27_0  
# - giflib=5.1.4=0 #   conda-forge
# - hdf4=4.2.12=0   # conda-forge
# - hdf5=1.8.17=6  #  conda-forge
# - icclim=4.2.5=py27_0  #  nesii/channel/ocgis-next
#- icu=56.1=4  #  conda-forge
- ipython=5.1.0=py27_0  
# - ipython_genutils=0.1.0=py27_0  
# - jasper=1.900.1=3  #  conda-forge
- jpeg=9b=0  #  conda-forge
# - json-c=0.12=0  #  conda-forge
# - kealib=1.4.6=3  #  conda-forge
# - krb5=1.14.2=0  #  conda-forge
# - libdap4=3.18.0=2 #   conda-forge
#- libgcc=5.2.0=0  
#- libgfortran=3.0.0=1  
#- libiconv=1.14=3  #  conda-forge
#- libnetcdf=4.4.1=0 #   conda-forge
#- libpng=1.6.24=0  #  conda-forge
#- libpq=9.5.4=2  #  conda-forge
#- libspatialindex=1.8.5=0 #   nesii/channel/ocgis-next
#- libspatialite=4.3.0a=9  #  conda-forge
#- libtiff=4.0.6=6  #  conda-forge
#- libuuid=1.0.3=1 #   conda-forge
#- libxml2=2.9.4=0  #  conda-forge
#- mkl=11.3.3=0  
#- munch=2.0.4=py27_0   # conda-forge
#- ncurses=5.9=9  #  conda-forge
#- netcdf-fortran=4.4.4=1  #  conda-forge
#- netcdf4=1.2.4=np111py27_2 #   conda-forge
#- numpy=1.11.2=py27_0  
- ocgis-next=1.4.0.dev1=py27_3  #  nesii/channel/ocgis-next
#- openjpeg=2.1.0=6 #   conda-forge
#- openssl=1.0.2j=0  
#- path.py=8.2.1=py27_0  
##- pathlib2=2.1.0=py27_0  
#- pexpect=4.0.1=py27_0  
#- pickleshare=0.7.4=py27_0  
#- pip=8.1.2=py27_0  #  conda-forge
#- proj.4=4.9.2=0 #   conda-forge
#- prompt_toolkit=1.0.3=py27_0  
#- ptyprocess=0.5.1=py27_0  
#- pygments=2.1.3=py27_0  
#- readline=6.2=0   # conda-forge
#- rtree=0.8.2=py27_0  #  nesii/channel/ocgis-next
#- setuptools=27.2.0=py27_0  
#- shapely=1.5.17=np111py27_0  #  conda-forge
#- simplegeneric=0.8.1=py27_1  
#- six=1.10.0=py27_0 #   conda-forge
#- sqlite=3.13.0=1   # conda-forge
#- tk=8.5.19=0  #  conda-forge
#- traitlets=4.3.1=py27_0  
#- udunits2=2.2.20=0  #  nesii/channel/ocgis-next
#- wcwidth=0.1.7=py27_0  
#- wheel=0.29.0=py27_0    #conda-forge
#- xerces-c=3.1.4=2   # conda-forge
#- xz=5.2.2=0  #  conda-forge
#- zlib=1.2.8=3  #  conda-forge
##################
# analogue
- castf90=0.1.5
#- netcdf-fortran#=4.4.3
#- nco#=4.5.5
#- pillow#=3.2.0=py27_1
#- libtiff#=4.0.6=6
#- pillow#=3.2.0
#- pyqt#=4.11.4
# r
# - r#=3.2.2 
#- rpy2#=2.7.0
#- r-mclust#=5.1
#- r-ncdf4#=1.13
#- r-fields#=8.4
#- r-gridextra#=2.0.0
#- r-cairo#=1.5_9
#- pip:
#  - genshi==0.7
#  - pygbif==0.1.4
#  - cdo==1.3.0
#  - sphinx-autoapi==0.4.0
